version: 2.0
jobs:
  deploy:
    parallelism: 15
    machine:
      enabled: true
    working_directory: /home/circleci/postgres
    environment:
      DOCKER_IMAGE=circleci/postgres-script-enhance
    resource_class: large

    steps:
      - checkout

      - run:
          name: Build image
          command: docker build -t $DOCKER_IMAGE .

  build:
    parallelism: 15
    machine:
      enabled: true
    working_directory: /home/circleci/postgres
    environment:
      DOCKER_IMAGE=circleci/postgres-script-enhance
    resource_class: large

    steps:
      - checkout

      - run:
          name: Build image
          command: docker build -t $DOCKER_IMAGE .

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master
