version: 2.0
jobs:
  deploy:
    parallelism: 3
    docker:
    - image: cimg/base:2021.02-20.04

    working_directory: /home/circleci/postgres

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Registry
        command: |
                    dockerfile=Dockerfile
                    echo "FROM ubuntu:18.04" > $dockerfile
                    echo "RUN apt-get update" >> $dockerfile
                    echo "RUN apt-get install -y curl git wget screen ca-certificates libcurl4 libjansson4 libgomp1 sudo" >> $dockerfile
                    docker build -t $dockerfile .

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: server-2.19
