version: 2.0
jobs:
  deploy:
    parallelism: 3
    docker:
    - image: cimg/base:2021.02-20.04
      environment:
        NAME: postgres-script-enhance
        CONTAINER_ORG: circleci
        DOCKERFILE_PATH: Dockerfile
        DOCKER_REGISTRY: dockerhub

    working_directory: /home/circleci/postgres

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Registry
        command: |
                    lscpu

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: server-2.19
